version: '3'

networks:
  default:
    external:
      name: wp-net

volumes:
    db:
      external: false
    blog:
      external: false

services:
  wp:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - blog:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wp-mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "12345"
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      default:
        aliases:
          - wp-mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "12345"
